[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[features]
default = ["gpu_ray_tracing"]
# default = []

gpu_ray_tracing = ["raven-engine/gpu_ray_tracing"]
dynamic_linking = ["raven-engine/dynamic_linking"]

[dependencies]
raven-engine = { path = "../../lib/raven-engine/" }

log = "0.4"       # logging lib
anyhow = "1.0.0"  # error lib